/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { SimpleContract } from "./SimpleContract";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export { SimpleContract__factory } from "./factories/SimpleContract__factory";
