/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export {DocumentCertification__factory} from "./DocumentCertification__factory";
export {Lock__factory} from "./Lock__factory";
