/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DocumentCertificationInterface extends Interface {
  getFunction(
    nameOrSignature: "certifyDocument" | "isCertifiedBy" | "isDocumentCertified"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DocumentCertified"): EventFragment;

  encodeFunctionData(
    functionFragment: "certifyDocument",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCertifiedBy",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDocumentCertified",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "certifyDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCertifiedBy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDocumentCertified",
    data: BytesLike
  ): Result;
}

export namespace DocumentCertifiedEvent {
  export type InputTuple = [_docHash: BytesLike, certifier: AddressLike];
  export type OutputTuple = [_docHash: string, certifier: string];
  export interface OutputObject {
    _docHash: string;
    certifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DocumentCertification extends BaseContract {
  connect(runner?: ContractRunner | null): DocumentCertification;
  waitForDeployment(): Promise<this>;

  interface: DocumentCertificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  certifyDocument: TypedContractMethod<
    [_docHash: BytesLike],
    [void],
    "nonpayable"
  >;

  isCertifiedBy: TypedContractMethod<
    [_certifier: AddressLike, _docHash: BytesLike],
    [boolean],
    "view"
  >;

  isDocumentCertified: TypedContractMethod<
    [_docHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "certifyDocument"
  ): TypedContractMethod<[_docHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isCertifiedBy"
  ): TypedContractMethod<
    [_certifier: AddressLike, _docHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDocumentCertified"
  ): TypedContractMethod<[_docHash: BytesLike], [boolean], "view">;

  getEvent(
    key: "DocumentCertified"
  ): TypedContractEvent<
    DocumentCertifiedEvent.InputTuple,
    DocumentCertifiedEvent.OutputTuple,
    DocumentCertifiedEvent.OutputObject
  >;

  filters: {
    "DocumentCertified(bytes32,address)": TypedContractEvent<
      DocumentCertifiedEvent.InputTuple,
      DocumentCertifiedEvent.OutputTuple,
      DocumentCertifiedEvent.OutputObject
    >;
    DocumentCertified: TypedContractEvent<
      DocumentCertifiedEvent.InputTuple,
      DocumentCertifiedEvent.OutputTuple,
      DocumentCertifiedEvent.OutputObject
    >;
  };
}
