/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Initializable } from "./@openzeppelin/contracts-upgradeable/proxy/utils/Initializable";
export { Initializable__factory } from "./factories/@openzeppelin/contracts-upgradeable/proxy/utils/Initializable__factory";
export type { DocumentCertification } from "./contracts/DocumentCertification";
export { DocumentCertification__factory } from "./factories/contracts/DocumentCertification__factory";
export type { Lock } from "./contracts/Lock";
export { Lock__factory } from "./factories/contracts/Lock__factory";
